export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL='PURCHASE_BURGER_FAIL' 
export const PURCHASE_BURGER_START='PURCHASE_BURGER_START'
export const PURCHASE_INIT = 'PURCHASE_INIT' 

export const FETCH_ORDER_START = 'FETCH_ORDER_START'
export const FETCH_ORDER_SUCCESS ='FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAIL ='FETCH_ORDER_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const CHANGE_PASSWORD_START= 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS= 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED= 'CHANGE_PASSWORD_FAILED'


export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_START = 'GET_CATEGORY_START'
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED'


export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START'
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'

export const UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START'
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START'
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'



export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_START = 'GET_PRODUCT_START'
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED'

export const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START'
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'

export const ADD_PRODUCT_START = 'ADD_PRODUCT_START'
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'

export const UPDATE_IMAGE_START = 'UPDATE_IMAGE_START'
export const UPDATE_IMAGE_FAILED = 'UPDATE_IMAGE_FAILED'
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS'

export const GET_STATISTIC_SUCCESS = 'GET_STATISTIC_SUCCESS'
export const GET_STATISTIC_START = 'GET_STATISTIC_START'
export const GET_STATISTIC_FAILED = 'GET_STATISTIC_FAILED'

export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS'
export const GET_STAFF_START = 'GET_STAFF_START'
export const GET_STAFF_FAILED = 'GET_STAFF_FAILED'

export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS'
export const UPDATE_STAFF_START = 'UPDATE_STAFF_START'
export const UPDATE_STAFF_FAILED = 'UPDATE_STAFF_FAILED'

export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS'
export const ADD_STAFF_START = 'ADD_STAFF_START'
export const ADD_STAFF_FAILED = 'ADD_STAFF_FAILED'

/**
 * CUSTOMER
 */
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS'
export const GET_CUSTOMER_START = 'GET_CUSTOMER_START'
export const GET_CUSTOMER_FAILED = 'GET_CUSTOMER_FAILED'

export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_START = 'UPDATE_CUSTOMER_START'
export const UPDATE_CUSTOMER_FAILED = 'UPDATE_CUSTOMER_FAILED'
//  ======================

export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_START = 'GET_ORDER_START'
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED'

export const GET_CANCELREASON_SUCCESS = 'GET_CANCELREASON_SUCCESS'
export const GET_CANCELREASON_START = 'GET_CANCELREASON_START'
export const GET_CANCELREASON_FAILED = 'GET_CANCELREASON_FAILED'

// Staff Portal
export const GET_STAFF_PROFILE_SUCCESS = 'GET_STAFF_PROFILE_SUCCESS'
export const GET_STAFF_PROFILE_START = 'GET_STAFF_PROFILE_START'
export const GET_STAFF_PROFILE_FAILED = 'GET_STAFF_PROFILE_FAILED'

export const UPDATE_STAFF_PROFILE_SUCCESS = 'UPDATE_STAFF_PROFILE_SUCCESS'
export const UPDATE_STAFF_PROFILE_START = 'UPDATE_STAFF_PROFILE_START'
export const UPDATE_STAFF_PROFILE_FAILED = 'UPDATE_STAFF_PROFILE_FAILED'

export const GET_AVAILABLE_PRODUCT_START='GET_AVAILABLE_PRODUCT_START'
export const GET_AVAILABLE_PRODUCT_SUCCESS='GET_AVAILABLE_PRODUCT_SUCCESS'
export const GET_AVAILABLE_PRODUCT_FAILED='GET_AVAILABLE_PRODUCT_FAILED'

export const ADD_ORDER_PRODUCT='ADD_ORDER_PRODUCT'
export const REMOVE_ORDER_PRODUCT='REMOVE_ORDER_PRODUCT'

export const PURCHASE_PRODUCT_SUCCESS = 'PURCHASE_PRODUCT_SUCCESS'
export const PURCHASE_PRODUCT_START='PURCHASE_PRODUCT_START' 
export const PURCHASE_PRODUCT_FAIL='PURCHASE_PRODUCT_FAIL'

export const DISSMISS_SUCCESS='DISSMISS_SUCCESS'

export const GET_CUSTOMER_ORDER_SUCCESS = 'GET_CUSTOMER_ORDER_SUCCESS'
export const GET_CUSTOMER_ORDER_START='GET_CUSTOMER_ORDER_START' 
export const GET_CUSTOMER_ORDER_FAIL='GET_CUSTOMER_ORDER_FAIL'

// Cancel Order Staff Side
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS'
export const CANCEL_ORDER_START = 'CANCEL_ORDER_START'
export const CANCEL_ORDER_FAILED = 'CANCEL_ORDER_FAILED'