export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL='PURCHASE_BURGER_FAIL' 
export const PURCHASE_BURGER_START='PURCHASE_BURGER_START'
export const PURCHASE_INIT = 'PURCHASE_INIT' 

export const FETCH_ORDER_START = 'FETCH_ORDER_START'
export const FETCH_ORDER_SUCCESS ='FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAIL ='FETCH_ORDER_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const CHANGE_PASSWORD_START= 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS= 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED= 'CHANGE_PASSWORD_FAILED'


export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_START = 'GET_CATEGORY_START'
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED'


export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START'
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'

export const UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START'
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START'
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
